# Generated by Django 4.1.3 on 2022-12-06 08:52

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gtn', models.IntegerField()),
                ('lot', models.IntegerField()),
                ('generic_name', models.CharField(max_length=50)),
                ('Date_exp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('date', models.IntegerField()),
                ('choises', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'امار افراد'), (2, 'مدیریت قفسه'), (3, 'ارسال پیغام'), (4, 'ثبت دارو'), (5, 'ثبت نسخه'), (6, 'مشاهده نسخه ثبت شده'), (7, 'جمع کردن دارو'), (8, 'مشاهده نسخه ثبت شده')], default=0, max_length=30)),
                ('phone_number', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.IntegerField()),
                ('price_main', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('store_number', models.IntegerField()),
                ('drugs', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='duapp.drug')),
            ],
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('store', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='duapp.store')),
            ],
        ),
        migrations.CreateModel(
            name='Cage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.IntegerField()),
                ('price_main', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('cage_number', models.IntegerField()),
                ('drugs', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='duapp.drug')),
            ],
        ),
    ]
