# Generated by Django 4.1.2 on 2022-12-07 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persondata',
            name='choises',
        ),
    ]
